# Using below prompt, I asked ChatGPT (plus) and Grok (SuperGrok) to get the below ai_term list
# I have split a 300MB text file into ~100 chunks (each chunk is plain text).
# The text is scientific papers about AI in cancer research. Your task is:
# 1. Read each chunk I upload.
# 2. Extract **all Artificial Intelligence–related terms** from the text.
#   - Include (but not limited to) techniques, methods, algorithms, tools, models, neural network architectures, NLP terms, computer vision terms, reinforcement learning terms, and related AI concepts.
#   - Capture synonyms, abbreviations, and variations (e.g., "SVM" and "support vector machine", "CNN" and "convolutional neural network") and save all the synonyms as separate item on a python list for each chunk.
# 3. Deduplicate them within each chunk.
# 4. After I upload all 100 chunks, merge and deduplicate the terms across all chunks into one **final comprehensive list**

ai_terms = [
    "Artificial Intelligence (AI)",
    "Explainable Artificial Intelligence (XAI / Explainable AI)",
    "Deep Learning (DL)",
    "Machine Learning (ML)",
    "Ensemble Learning",
    "Transfer Learning",
    "Semi-Supervised Learning",
    "Supervised Learning",
    "Attention Mechanism",
    "Self-Attention Transformer",
    "Transformer Networks",
    "SwinV2 Transformer",
    "Contrastive Transformer",
    "Graph Transformer",
    "Convolutional Neural Network (CNN)",
    "Dense Convolutional Network",
    "Residual Network (ResNet, ResNetv2)",
    "VGG16",
    "VGG19",
    "GoogLeNet",
    "U-Net",
    "3D U-Net",
    "Customized U-Net",
    "Mask R-CNN",
    "Scat Inception Model",
    "Attention-Based Dilated Bridge Net (ADB-Net)",
    "Sparse Supervised Autoencoder Neural Network (SSAE)",
    "Deep Belief Network (DBN)",
    "Restricted Boltzmann Machine (RBM / CRBM)",
    "Bayesian Network",
    "Support Vector Machine (SVM)",
    "Graph Neural Network (GNN)",
    "Graph Convolutional Neural Network (GCN)",
    "Hierarchical Refinement Graph Convolutional Neural Network (HRGCN)",
    "Neural Network",
    "Independent Component Analysis (ICA)",
    "Feature Extraction",
    "Feature Selection Algorithms",
    "Genetic Algorithm (GA)",
    "Dragonfly Optimization (DFO)",
    "Jaya Optimization Algorithm",
    "CatBoost",
    "Quantitative Structure–Activity Relationship (QSAR) models",
    "Pharmacophore Modeling",
    "Decision Support Systems",
    "Computer-Aided Diagnosis (CAD / CADx)",
    "Image Segmentation Algorithms",
    "Object Detection",
    "Camouflage Object Detection",
    "Polyp Detection",
    "Disease Forecasting Models",
    "Knowledge Graphs",
    "Natural Language Processing (NLP)",
    "CRF Decoder",
    "deep learning",
    "resnetv2",
    "hyperparameter optimizer",
    "classification",
    "Boltzmann machine",
    "deep belief network",
    "crbm",
    "dbn",
    "simulated validation",
    "deep learning model",
    "u net architecture",
    "dice similarity coefficient",
    "structural similarity index",
    "support vector machine",
    "svm",
    "deep learning segmentation model",
    "u net",
    "machine learning",
    "gsea",
    "kegg",
    "predictive performance",
    "image enhancement",
    "non-local mean filter",
    "clahe",
    "gamma correction",
    "squeeze excitation",
    "spatial pyramid pooling",
    "cnn",
    "multimodal",
    "ablation study",
    "image processing",
    "feature extraction",
    "residual network",
    "self attention",
    "transformer",
    "attention mechanism",
    "spatial attention",
    "convolutional neural network",
    "unet",
    "squeeze excitation block",
    "spatial pyramid pooling layer",
    "machine learning base",
    "random forest",
    "gradient boosting",
    "transfer learning",
    "pre-processing",
    "convolution block",
    "mask rcnn",
    "reinforcement learning",
    "image classification",
    "squeeze excitation block",
    "ml",
    "machine learning classifier",
    "neuronal network",
    "network pharmacology",
    "genetic algorithm",
    "predictive modeling",
    "deep neural network",
    "non-invasive",
    "feature importance",
    "lstm",
    "transformer",
    "ai model",
    "classification network",
    "predictive model",
    "predictive biomarkers",
    "microRNA",
    "cnns",
    "detection",
    "machine learning algorithms",
    "radiomics",
    "deep learning model",
    "neural networks",
    "multi-agent systems",
    "liver cancer prediction",
    "bioinformatics",
    "protein kinase inhibitors",
    "xgboost",
    "machine learning models",
    "adaboost",
    "neuroimaging",
    "svm classifier",
    "data mining",
    "multi-omics analysis",
    "deep learning algorithms",
    "early detection",
    "transcriptomic",
    "biomarker",
    "tcr prediction",
    "class activation mapping",
    "generative adversarial network",
    "gan",
    "image processing",
    "active contour model",
    "acm",
    "boltzmann machine",
    "deep belief network",
    "crbm",
    "deep neural network",
    "u-net",
    "xgboost",
    "random forest",
    "gradient boosting",
    "mask rcnn",
    "image segmentation",
    "residual network",
    "squeeze excitation",
    "self attention",
    "attention mechanism",
    "transfer learning",
    "preprocessing",
    "spatial pyramid pooling",
    "predictive modeling",
    "gsea",
    "kegg",
    "machine learning classifier",
    "lstm",
    "reinforcement learning",
    "bioinformatics",
    "protein kinase inhibitors",
    "radiomics",
    "prediction model",
    "classification",
    "segmentation",
    "neuronal network",
    "multi-agent systems",
    "multi-omics analysis",
    "svm classifier",
    "predictive biomarkers",
    "deep neural network",
    "data mining",
    "neuroimaging",
    "neural networks",
    "machine learning models",
    "gene expression",
    "biomarkers",
    "protein biomarkers",
    "medical imaging",
    "radiology",
    "mri",
    "convolutional neural network",
    "mlp",
    "deep convolutional neural network",
    "catboost",
    "random forest classifier",
    "deep learning segmentation",
    "transfer learning",
    "ablation study",
    "classifier",
    "predictive biomarkers",
    "classification network",
    "gene ontology",
    "data mining algorithms",
    "image classification",
    "multimodal",
    "reinforcement learning",
    "neuroimaging",
    "artificial intelligence",
    "deep learning",
    "convolutional neural network",
    "cnn",
    "support vector machine",
    "svm",
    "transformer",
    "recurrent neural network",
    "rnn",
    "reinforcement learning",
    "generative adversarial network",
    "gan",
    "neural network",
    "image classification",
    "machine learning",
    "random forest",
    "gradient boosting",
    "xgboost",
    "decision tree",
    "transfer learning",
    "mask rcnn",
    "feature extraction",
    "data mining",
    "predictive modeling",
    "segmentation",
    "predictive biomarkers",
    "lstm",
    "biomarker",
    "data analysis",
    "neuroimaging",
    "predictive performance",
    "model evaluation",
    "ai model",
    "artificial neural network",
    "gan model",
    "deep neural network",
    "machine learning model",
    "reinforcement learning",
    "deep belief network",
    "dbn",
    "deep convolutional neural network",
    "deep learning segmentation",
    "self attention",
    "attention mechanism",
    "u-net",
    "cnn architecture",
    "image enhancement",
    "spatial pyramid pooling",
    "non-invasive",
    "multi-agent systems",
    "bioinformatics",
    "radiomics",
    "biomarker discovery",
    "multi-modal",
    "clinical data",
    "multi-omics",
    "predictive model",
    "ai model performance",
    "reinforcement learning models",
    "transfer learning models",
    "neural architecture",
    "ensemble learning",
    "machine learning classification",
    "neural network classification",
    "feature importance",
    "reinforcement learning models",
    "transfer learning methods",
    "deep convolutional networks",
    "image processing",
    "bioinformatics",
    "multimodal model",
    "deep neural network algorithms",
    "svm classifier",
    "ai-assisted model",
    "deep learning algorithms",
    "artificial intelligence",
    "deep learning",
    "convolutional neural network",
    "cnn",
    "support vector machine",
    "svm",
    "transformer",
    "reinforcement learning",
    "generative adversarial network",
    "gan",
    "machine learning",
    "xgboost",
    "random forest",
    "gradient boosting",
    "decision tree",
    "image classification",
    "mask rcnn",
    "transfer learning",
    "residual network",
    "self attention",
    "attention mechanism",
    "u-net",
    "lstm",
    "bioinformatics",
    "radiomics",
    "predictive modeling",
    "predictive biomarkers",
    "svm classifier",
    "neuroimaging",
    "multi-agent systems",
    "image segmentation",
    "image enhancement",
    "spatial pyramid pooling",
    "feature extraction",
    "feature importance",
    "classification network",
    "recurrent neural network",
    "rnn",
    "deep neural network",
    "predictive performance",
    "multi-omics analysis",
    "bioinformatics",
    "reinforcement learning models",
    "neural network classification",
    "biomarkers",
    "xgboost model",
    "classifier",
    "mask rcnn",
    "early detection",
    "medical imaging",
    "neural networks",
    "image processing",
    "deep convolutional neural network",
    "deep belief network",
    "svm classifier",
    "machine learning models",
    "data mining",
    "transformer architecture",
    "preprocessing",
    "classifier performance",
    "artificial intelligence",
    "deep learning",
    "convolutional neural network",
    "cnn",
    "support vector machine",
    "svm",
    "transformer",
    "reinforcement learning",
    "generative adversarial network",
    "gan",
    "neural network",
    "image classification",
    "machine learning",
    "random forest",
    "gradient boosting",
    "xgboost",
    "decision tree",
    "transfer learning",
    "mask rcnn",
    "residual network",
    "self attention",
    "attention mechanism",
    "u-net",
    "lstm",
    "bioinformatics",
    "radiomics",
    "predictive modeling",
    "predictive biomarkers",
    "svm classifier",
    "neuroimaging",
    "predictive performance",
    "machine learning model",
    "reinforcement learning models",
    "deep neural network",
    "data mining",
    "image enhancement",
    "spatial pyramid pooling",
    "non-invasive",
    "multi-agent systems",
    "multi-modal",
    "bioinformatics",
    "image segmentation",
    "image enhancement",
    "neural network classifier",
    "neural networks",
    "machine learning models",
    "xgboost model",
    "transfer learning models",
    "preprocessing",
    "image processing",
    "feature extraction",
    "neural network architecture",
    "data mining algorithms",
    "multi-omics",
    "svm classifier",
    "predictive biomarkers",
    "deep neural network algorithms",
    "early detection",
    "image processing",
    "deep learning algorithms",
    "multi-omics analysis",
    "support vector machine classifier",
    "svm classifier",
    "reinforcement learning models",
    "neuroimaging",
    "neural networks",
    "deep learning model",
    "predictive biomarkers",
    "multi-modal model",
    "reinforcement learning",
    "svm model",
    "deep neural network",
    "artificial intelligence",
    "deep learning",
    "machine learning",
    "multiple instance learning",
    "attention mechanism",
    "vision transformer",
    "transformer",
    "convolutional neural network",
    "cnn",
    "radiomic",
    "radiomics",
    "radiomic feature",
    "image segmentation",
    "computer assisted diagnosis",
    "computer assisted tomography",
    "image analysis",
    "image reconstruction",
    "image processing",
    "weakly supervised learning",
    "supervised classification",
    "support vector machine",
    "svm",
    "random forest",
    "decision tree",
    "lasso regression",
    "cox regression model",
    "predictive model",
    "classification model",
    "prognostic model",
    "machine learning model",
    "interpretable machine learning",
    "algorithm",
    "feature extraction",
    "feature selection",
    "sequential feature selection",
    "xgboost",
    "lightgbm",
    "neural network",
    "dnn",
    "mlp",
    "graph neural network",
    "graph learning",
    "knowledge graph",
    "representation learning",
    "multi-task learning",
    "weakly supervised classification",
    "pattern recognition",
    "image classification",
    "learning model",
    "attention-based model",
    "salient instance inference",
    "meta-analysis of deep learning models",
    "artificial intelligence",
    "machine learning",
    "deep learning",
    "convolutional neural network",
    "cnn",
    "recurrent neural network",
    "rnn",
    "long short term memory",
    "lstm",
    "support vector machine",
    "svm",
    "naive bayes",
    "decision tree",
    "random forest",
    "k nearest neighbor",
    "knn",
    "gradient boosting",
    "xgboost",
    "lightgbm",
    "transfer learning",
    "reinforcement learning",
    "unsupervised learning",
    "supervised learning",
    "semi supervised learning",
    "self supervised learning",
    "predictive model",
    "classification model",
    "clustering",
    "dimensionality reduction",
    "principal component analysis",
    "pca",
    "natural language processing",
    "nlp",
    "image segmentation",
    "image recognition",
    "computer vision",
    "pattern recognition",
    "feature extraction",
    "feature selection",
    "regression model",
    "cox regression model",
    "lasso regression",
    "graph neural network",
    "gnn",
    "transformer",
    "vision transformer",
    "attention mechanism",
    "attention based model",
    "representation learning",
    "multi-task learning",
    "interpretability",
    "explainable ai",
    "knowledge graph",
    "meta learning",
    "bayesian network",
    "probabilistic model",
    "algorithm",
    "data mining",
    "predictive analytics",
    "artificial intelligence",
    "machine learning",
    "deep learning",
    "convolutional neural network",
    "cnn",
    "recurrent neural network",
    "rnn",
    "long short term memory",
    "lstm",
    "support vector machine",
    "svm",
    "naive bayes",
    "decision tree",
    "random forest",
    "k nearest neighbor",
    "knn",
    "gradient boosting",
    "xgboost",
    "lightgbm",
    "transfer learning",
    "reinforcement learning",
    "unsupervised learning",
    "supervised learning",
    "semi supervised learning",
    "self supervised learning",
    "predictive model",
    "classification model",
    "clustering",
    "dimensionality reduction",
    "principal component analysis",
    "pca",
    "natural language processing",
    "nlp",
    "image segmentation",
    "image recognition",
    "computer vision",
    "pattern recognition",
    "feature extraction",
    "feature selection",
    "regression model",
    "cox regression model",
    "lasso regression",
    "graph neural network",
    "gnn",
    "transformer",
    "vision transformer",
    "attention mechanism",
    "attention based model",
    "representation learning",
    "multi-task learning",
    "interpretability",
    "explainable ai",
    "knowledge graph",
    "meta learning",
    "bayesian network",
    "probabilistic model",
    "algorithm",
    "data mining",
    "predictive analytics"
]
